name: Deploy Backend to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_USERNAME: ${{ secrets.HF_USERNAME || 'nishantmakwanaa' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Verify Secrets
        run: |
          echo "HF Username: $HF_USERNAME"

          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN missing"
            exit 1
          fi

          echo "HF_TOKEN configured"

      - name: Prepare Backend Deployment
        run: |
          mkdir /tmp/hf-deploy

          rsync -av backend/ /tmp/hf-deploy \
            --exclude ".env" \
            --exclude ".env.*" \
            --exclude "__pycache__" \
            --exclude "*.pyc"

          cd /tmp/hf-deploy

          git init -b main

          git lfs install

          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/plant-disease-detection-app

          git add .

          git commit -m "Deploy backend from GitHub Actions"

      - name: Push Backend to Hugging Face
        run: |
          cd /tmp/hf-deploy
          git push --force hf main

